# Generated by Django 5.1.1 on 2024-09-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invApp', '0002_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.IntegerField(max_length=100, unique=True),
        ),
    ]
